# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  pkgs,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usb_storage" "sd_mod"];
    initrd.kernelModules = [];
    blacklistedKernelModules = [
      "i2c_piix4"
      "8250_core"
    ];
    kernelModules = [
      "kvm-amd"
      "nvidia"
      "nvidia_uvm"
      "nvidia_modeset"
    ];
    extraModulePackages = [];

    kernelParams = [
      "8250.nr_uarts=0"
    ];
  };

  services.xserver = {
    videoDrivers = ["nvidia" "displaylink" "modesettings"];
    displayManager.sessionCommands = ''
      ${lib.getBin pkgs.xorg.xrandr}/bin/xrandr --setprovideroutputsource 2 0
    '';
  };

  security.sudo.extraConfig = ''
    Defaults        timestamp_timeout=30
  '';

  hardware.nvidia = {
    modesetting.enable = true;

    open = true;
    nvidiaSettings = true;

    prime = {
      nvidiaBusId = "PCI:1:0:0";
      amdgpuBusId = "PCI:4:0:0";

      offload = {
        enable = true;
        enableOffloadCmd = true;
      };

      sync.enable = false;
    };
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/b52785cc-94cb-43c8-b16d-540c915b29c7";
      fsType = "ext4";
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/109A-6458";
      fsType = "vfat";
      options = ["fmask=0077" "dmask=0077"];
    };

    # Example for the Windows partition (p3)
    #    "/mnt/windows" = {
    #      device = "/dev/disk/by-uuid/894d0ff5-a064-449c-b0ea-c96c8dee8877";
    #      fsType = "ntfs"; # Assuming NTFS
    #      options = ["nofail" "x-systemd.device-timeout=500ms"]; # 🟢 Crucial change
    #    };
    #
    #    # Example for the RECOVERY partition (p4)
    #    "/mnt/recovery" = {
    #      device = "/dev/disk/by-uuid/E69632A9963279DF";
    #      fsType = "ntfs"; # Or appropriate type
    #      options = ["nofail" "x-systemd.device-timeout=500ms"]; # 🟢 Crucial change
    #    };
  };

  # Repeat for /dev/nvme0n1p5 and /dev/nvme0n1p2 if they are defined as mounts.
  # If they are not mounted, this wait time is Udev's device discovery phase, which is harder to fix.
  # Applying 'nofail' to all non-essential mounts is the best solution here.

  swapDevices = [
    {
      device = "/var/lib/swapfile";
      size = 16 * 1024;
    }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
